language: node_js
node_js:
  - "node"
cache:
  yarn: true,
  directories:
    - node_modules
before_script:
  - npm install -g yarn
  - travis_retry yarn install
script:
  - yarn build-css
  - travis_retry yarn test
  - travis_retry yarn build

