export const AJAX_CALL_BEGIN = 'AJAX_CALL_BEGIN';

export const LOGOUT = 'LOGOUT';

export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_CHILDREN_SUCCESS = "LOAD_CHILDREN_SUCCESS";

export const LOAD_LESSONS_SUCCESS = "LOAD_LESSONS_SUCCESS";
export const LOAD_LESSON_SLIDES_SUCCESS = "LOAD_LESSON_SLIDES_SUCCESS";

export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_COURSES_ERROR = "FETCH_COURSES_ERROR";

export const FETCH_CHILDREN = "FETCH_CHILDREN";
export const FETCH_CHILDREN_ERROR = "FETCH_CHILDREN_ERROR";

export const FETCH_LESSONS = "FETCH_LESSONS";
export const FETCH_LESSONS_ERROR = "FETCH_LESSONS_ERROR";

export const FETCH_LESSON_SLIDES = "FETCH_LESSON_SLIDES";
export const FETCH_LESSON_SLIDES_ERROR = "FETCH_LESSON_SLIDES_ERROR";

export const BEGIN_LOGIN = "BEGIN_LOGIN";
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCES = 'LOGIN_SUCCESS';

export const FETCH_LEVELS_START = "FETCH_LEVELS_START";
export const FETCH_LEVELS_SUCCESS = "FETCH_LEVELS_SUCCESS";
export const FETCH_LEVELS_ERROR = "FETCH_LEVELS_ERROR";

export const FETCH_GROUPS_START = "FETCH_GROUPS_START";
export const FETCH_GROUPS_SUCCESS = "FETCH_GROUPS_SUCCESS";
export const FETCH_GROUPS_ERROR = "FETCH_GROUPS_ERROR";

export const POST_ATTENDANCE_START = "POST_ATTENDANCE_START";
export const POST_ATTENDANCE_SUCCESS = "POST_ATTENDANCE_SUCCESS";
export const POST_ATTENDANCE_ERROR = "POST_ATTENDANCE_ERROR";
