export const AJAX_CALL_BEGIN = 'AJAX_CALL_BEGIN';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Authorization
export const LOGIN_SUCCES = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

// Courses
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_CHILDREN_SUCCESS = "LOAD_CHILDREN_SUCCESS";


// Lessons
export const LOAD_LESSONS_SUCCESS = "LOAD_LESSONS_SUCCESS";
export const LOAD_LESSON_SLIDES_SUCCESS = "LOAD_LESSON_SLIDES_SUCCESS";


// Calendar
export const LOAD_CALENDAR_SUCCESS = "LOAD_CALENDAR_SUCCESS";


// Courses
export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_CHILDREN = "FETCH_CHILDREN";

// Lessons
export const FETCH_LESSONS = "FETCH_LESSONS";
export const FETCH_LESSON_SLIDES = "FETCH_LESSON_SLIDES";

// Calendar
export const FETCH_CALENDAR = "FETCH_CALENDAR";

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const FETCH_COURSES_ERROR = "FETCH_COURSES_ERROR";
export const FETCH_CHILDREN_ERROR = "FETCH_CHILDREN_ERROR";
export const FETCH_CALENDAR_ERROR = "FETCH_CALENDAR_ERROR";
export const FETCH_LESSON_SLIDES_ERROR = "FETCH_LESSON_SLIDES_ERROR";
export const FETCH_LESSONS_ERROR = "FETCH_LESSONS_ERROR";


export const BEGIN_LOGIN = "BEGIN_LOGIN";

export const REFRESH_STORE = "REFRESH_STORE";

export const FETCH_LEVELS = "FETCH_LEVELS";
export const LOAD_LEVELS_SUCCESS = "LOAD_LEVELS_SUCCESS";
export const FETCH_LEVELS_ERROR = "FETCH_LEVELS_ERROR";

export const FETCH_GROUPS = "FETCH_GROUPS";
export const LOAD_GROUPS_SUCCESS = "LOAD_GROUPS_SUCCESS";
export const FETCH_GROUPS_ERROR = "FETCH_GROUPS_ERROR";

export const MARK_PRESENCE = "MARK_PRESENCE";
export const MARK_PRESENCE_SUCCESS = "MARK_PRESENCE_SUCCESS";
export const MARK_PRESENCE_ERROR = "MARK_PRESENCE_ERROR";
