export const AJAX_CALL_BEGIN = 'AJAX_CALL_BEGIN';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Authorization
export const LOGIN_SUCCES = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

// Courses
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";
export const LOAD_CHILDREN_SUCCESS = "LOAD_CHILDREN_SUCCESS";


// Lessons
export const LOAD_LESSONS_SUCCESS = "LOAD_LESSONS_SUCCESS";
export const LOAD_LESSON_SLIDES_SUCCESS = "LOAD_LESSON_SLIDES_SUCCESS";


// Calendar
export const LOAD_CALENDAR_SUCCESS = "LOAD_CALENDAR_SUCCESS";
