export const STATUS_TEACHERISFORESEEN = 'STATUS_TEACHERISFORESEEN';
export const STATUS_TEACHERDOESREPLACEMENT = 'STATUS_TEACHERDOESREPLACEMENT';
export const STATUS_TEACHERISREPLACED = 'STATUS_TEACHERISREPLACED';
