export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_COURSES_ERROR = "FETCH_COURSES_ERROR";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS";

export const FETCH_CHILDREN = "FETCH_CHILDREN";
export const FETCH_CHILDREN_ERROR = "FETCH_CHILDREN_ERROR";
export const LOAD_CHILDREN_SUCCESS = "LOAD_CHILDREN_SUCCESS";
