export const FETCH_LESSONS_START = 'FETCH_LESSONS_START';
export const FETCH_LESSONS_SUCCESS = 'LOAD_LESSONS_SUCCESS';
export const FETCH_LESSONS_ERROR = 'FETCH_LESSONS_ERROR';
export const FETCH_ATTENDANCES_START = 'FETCH_ATTENDANCES_START';
export const FETCH_ATTENDANCES_SUCCESS = 'FETCH_ATTENDANCES_SUCCESS';
export const FETCH_ATTENDANCES_ERROR = 'FETCH_ATTENDANCES_ERROR';
