export const FETCH_LESSONS_START = "FETCH_LESSONS_START";
export const FETCH_LESSONS_SUCCESS = "LOAD_LESSONS_SUCCESS";
export const FETCH_LESSONS_ERROR = "FETCH_LESSONS_ERROR";

export const FETCH_LESSON_SLIDES_START = "FETCH_LESSON_SLIDES_START";
export const FETCH_LESSON_SLIDES_SUCCESS = "FETCH_LESSON_SLIDES_SUCCESS";
export const FETCH_LESSON_SLIDES_ERROR = "FETCH_LESSON_SLIDES_ERROR";
