export const FETCH_LEVELS = "FETCH_LEVELS";
export const LOAD_LEVELS_SUCCESS = "LOAD_LEVELS_SUCCESS";
export const FETCH_LEVELS_ERROR = "FETCH_LEVELS_ERROR";

export const FETCH_GROUPS = "FETCH_GROUPS";
export const LOAD_GROUPS_SUCCESS = "LOAD_GROUPS_SUCCESS";
export const FETCH_GROUPS_ERROR = "FETCH_GROUPS_ERROR";
