export const FETCH_LESSON_SLIDES_START = 'FETCH_LESSON_SLIDES_START';
export const FETCH_LESSON_SLIDES_SUCCESS = 'FETCH_LESSON_SLIDES_SUCCESS';
export const FETCH_LESSON_SLIDES_ERROR = 'FETCH_LESSON_SLIDES_ERROR';
