export const POST_ATTENDANCE_START = 'POST_ATTENDANCE_START';
export const POST_ATTENDANCE_SUCCESS = 'POST_ATTENDANCE_SUCCESS';
export const POST_ATTENDANCE_ERROR = 'POST_ATTENDANCE_ERROR';

export const FETCH_PROFILE_START = 'FETCH_PROFILE_START';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_ERROR = 'FETCH_PROFILE_ERROR';

export const UPDATE_PROFILE_START = 'UPDATE_PROFILE_START';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';
